/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 05 15:21:42 GMT 2021
 */

package comp5111.assignment.cut;

import org.junit.Test;
import static org.junit.Assert.*;
import comp5111.assignment.cut.ToolBox_ESTest;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

//@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ToolBox_ESTest_ESTest{

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ToolBox_ESTest toolBox_ESTest0 = new ToolBox_ESTest();
  }
}
